### ISSUE TITLE
gtrend_scraper errors

### ISSUE THREAD

**Issue by hack-r** [trinker/gtrend#3]
When I run gtrend_scraper with the example code and my username/password, I get errors like this:

> out <- gtrend_scraper("user@gmail.com", "password", terms)
> [1] "Substituting sparse Google Trends (monthly) with NA series"
> Error in as.character(x) : 
>   cannot coerce type 'closure' to vector of type 'character'
> [1] "Substituting sparse Google Trends (monthly) with NA series"
> Error in as.character(x) : 
>   cannot coerce type 'closure' to vector of type 'character'

I get a similar error when specifying the function call in the following way:

> out <- gtrend_scraper(username = "user@gmail.com", password = "password", phrases = "Big Data") 
> [1] "Substituting sparse Google Trends (monthly) with NA series"
> Error in as.character(x) : 
>   cannot coerce type 'closure' to vector of type 'character'
> No trend data for:
> "Big Data"

Perhaps the package is broken due to changes on Google's side? When I dig a little deeper I find this value (in part) resulting from a failed attempt to use the underlying gtrends() function of GTrendsR:

$headers
[1] "HTTP/1.1 302 Moved Temporarily\r"

**Comment by trinker** [comment]
@hack-r Thanks for opening this.

If you want to fix pull requests are welcomed.  For the foreseeable future I am writing on my thesis and gtrends is un-related to that work.  I'll try it out tonight and at the very least put a note of this in the README if what you're saying is reproducible.

**Comment by hack-r** [comment]
Oh, ok! Let me see what I can do.

I understand the pressures of a thesis. Been there myself (twice, actually). Good luck with it!

**Comment by jamespbrink** [comment]
hack-r did you ever resolve this?  I am having the same issue.

**Comment by trinker** [comment]
@hack-r I can't reproduce your error.  I had a new error that came from upstream that was resulting in quotes wrapping terms but fixed that today.  I pushed to GitHub.  Try the new version.  The error indicates a function name is being passed to something.

**Comment by yanhann10** [comment]
I got an error to install GTrendsR when it's already installed. 
Loading required package: GTrendsR
GTrendsR package not found.
Should I attempt to get from GitHub?

wonder if it's lowercase gtrendsR instead. 
but pls ignore it if this package is no longer maintained. thanks.

**Comment by trinker** [comment]
This package is gtrend not gtrendsr.  This is an unsupported github package.  The package you are looking for is on CRAN along with how to contact the maintainer.

**Comment by yanhann10** [comment]
was actually referring to this line: reqcheck <- suppressWarnings(require("GTrendsR"))
i know my earlier msg can cause confusion. please ignore it. no support needed.

**Comment by hack-r** [comment]
Tyler, speaking of it being unsupported shall we go ahead and close this thread? It's pretty ancient.

**********************************
Sent using Voice to Text so if there are errors, that's probably why

**Comment by hack-r** [comment]
Closed on account of this thread being ancient and attracting unrelated questions/issues.
